name: ragify_flutter
description: "Intelligent Context Orchestration Framework for Flutter - Smart Context for LLM-Powered Applications"
version: 0.0.4
homepage: https://github.com/sumitnemade/ragify_flutter
repository: https://github.com/sumitnemade/ragify_flutter
issue_tracker: https://github.com/sumitnemade/ragify_flutter/issues
documentation: https://github.com/sumitnemade/ragify_flutter/blob/main/README.md
  
  ^1.5.0
topics:
  - ai
  - rag
  - context-management
  - retrieval-augmented-generation
  - llm

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

# Platform support
flutter:
  # No UI components - this is a pure logic package
  # Supports all platforms: Android, iOS, Web, Windows, macOS, Linux
  # Uses conditional imports for platform-specific features

# Platform-specific dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.5.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  
  # Async and concurrency
  async: ^2.13.0
  
  # Cross-platform ML and vector operations
  # Using AI Model APIs only - no local models
  
  # Cross-platform database and storage
  # Mobile: Hive + shared_preferences, Web: Hive, Desktop: Hive + file_system
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  
  # Platform-specific database drivers (conditional imports)
  sqflite: ^2.4.2  # Android, iOS, macOS
  postgres: ^3.5.6  # All platforms
  mysql1: ^0.20.0  # All platforms
  mongo_dart: ^0.10.5  # All platforms
  
  # Cross-platform document processing
  path: ^1.9.1
  path_provider: ^2.1.5
  
  # Cross-platform security and encryption
  crypto: ^3.0.6
  encrypt: ^5.0.3
  
  # Cross-platform real-time communication
  web_socket_channel: ^3.0.3
  
  # Logging and debugging
  logger: ^2.6.1
  
  # State management
  provider: ^6.1.5+1
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  mockito: ^5.5.0
  lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
